// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-20 13:44:23
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure for table file.
type File struct {
	Id        uint        `json:"id"        ` // FILE ID
	CreatedAt *gtime.Time `json:"createdAt" ` // 文件创建时间
	Name      string      `json:"name"      ` // 文件名
	Md5       string      `json:"md5"       ` // 文件MD5值
	Size      int64       `json:"size"      ` // 文件大小
	Path      string      `json:"path"      ` // 文件存储目录
	Import    int         `json:"import"    ` // 文件是否被处理,默认未处理
}
