// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-20 13:44:23
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Image is the golang structure for table image.
type Image struct {
	Id        uint        `json:"id"        ` // image auto increment ID
	CreatedAt *gtime.Time `json:"createdAt" ` // 镜像记录创建时间
	New       string      `json:"new"       ` // 更改后的新镜像名称
	Old       string      `json:"old"       ` // 上传的镜像名称
	FileId    int         `json:"fileId"    ` // 对应文件自增ID
}
