// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-11 10:34:15
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint        `json:"id"       ` // User ID
	Passport string      `json:"passport" ` // User Passport
	Password string      `json:"password" ` // User Password
	Nickname string      `json:"nickname" ` // User Nickname
	CreateAt *gtime.Time `json:"createAt" ` // Created Time
	UpdateAt *gtime.Time `json:"updateAt" ` // Updated Time
}
