# HTTP Server.
server:
  address: ":9527"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  ClientMaxBodySize: "1000MB"

# Global logging.
logger:
    level: "all"
    stdout: true

# Database.
database:
  logger:
    level: "all"
    stdout: true

  default:
    link: "mysql:root:nBqYwcAq^MJCx^KJ@tcp(1.14.22.216:3306)/pornhub"
    debug: true

# gfcli tools
gfcli:
  gen:
    dao:
    - link: "mysql:root:nBqYwcAq^MJCx^KJ@tcp(1.14.22.216:3306)/pornhub"

file:
  filePath: "files"

harbor:
  ip: "172.27.15.153"
  username: "admin"
  password: "Harbor12345"

