# HTTP Server.
server:
  address: ":9527"
  dumpRouterMap: true
  routeOverWrite: true
  accessLogEnabled: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  ClientMaxBodySize: "10000MB"
  errorLogEnabled: true

# Global logging.
logger:
  path: "D:\\run\\logs"
  file: "app-{Y-m-d}.log"
  level: "all"
  stdout: true
  rotateSize: "100M"
  rotateBackupLimit: 5
  rotateBackupExpire: "5d"
  rotateBackupCompress: 9
  rotateCheckInterval: "24h"

# Database.
database:
  logger:
    path: "D:\\run\\logs"
    file: "sql-{Y-m-d}.log"
    level: "all"
    stdout: true
    rotateSize: "100M"
    rotateBackupLimit: 5
    rotateBackupExpire: "5d"
    rotateBackupCompress: 9
    rotateCheckInterval: "24h"

  default:
    link: "mysql:root:nBqYwcAq^MJCx^KJ@tcp(127.0.0.1:3306)/sakura"
    debug: true

# gfcli tools
gfcli:
  gen:
    dao:
    - link: "mysql:root:nBqYwcAq^MJCx^KJ@tcp(127.0.0.1:3306)/sakura"

file:
  filePath: "D:\\run\\files"

harbor:
  ip: "172.27.15.122"
  username: "admin"
  password: "Harbor12345"

kube:
  configPath: "D:\\run\\conf"

update:
  uncompressedPath: "D:\\run\\update"

