// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-20 13:44:23
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Image is the golang structure of table image for DAO operations like Where/Data.
type Image struct {
	g.Meta    `orm:"table:image, do:true"`
	Id        interface{} // image auto increment ID
	CreatedAt *gtime.Time // 镜像记录创建时间
	New       interface{} // 更改后的新镜像名称
	Old       interface{} // 上传的镜像名称
	FileId    interface{} // 对应文件自增ID
}
