// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"zhangyudevops.com/internal/model/service/internal/dao/internal"
)

// imageDao is the data access object for table image.
// You can define custom methods on it to extend its functionality as you wish.
type imageDao struct {
	*internal.ImageDao
}

var (
	// Image is globally public accessible object for table image operations.
	Image = imageDao{
		internal.NewImageDao(),
	}
)

// Fill with you ideas below.
